name: "Release: transformer-ranker pypi"

on:
  push:
    tags:
      - 'v*.*.*'  # run on new version tags >v0.1.3

jobs:
  build:
    name: build + prepare for publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
  
      - name: deps
        run: pip install --upgrade pip build twine

      - name: version sanity check
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
          [ "$TAG" = "$VERSION" ] || { echo "Tag $TAG ≠ $VERSION in pyproject.toml" && exit 1; }

      - name: build package
        run: python -m build

      - name: twine check
        run: twine check dist/*

      - name: stash dist
        uses: actions/upload-artifact@v4
        with:
          name: python-package-dist
          path: dist/

  testpypi:
    name: publish -> testpypi
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/transformer-ranker/
    permissions:
      id-token: write

    steps:
      - name: download distribution artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-dist
          path: dist/
  
      - name: upload -> testpypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  release:
    name: publish -> pypi
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/transformer-ranker/
    permissions:
      id-token: write

    steps:
      - name: download distribution artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-dist
          path: dist/

      - name: show banner
        run: |
          echo ""
          echo "  // transformer-ranker v${GITHUB_REF#refs/tags/v}"
          echo " ╭-------------------------------------------╮"
          echo " |  uploading transformer-ranker to pypi ;p  |"
          echo " ╰-------------------------------------------╯"
          echo ""

      - name: upload -> pypi
        uses: pypa/gh-action-pypi-publish@release/v1
