name: Python Package Release

on:
  push:
    tags:
      - 'v*.*.*'  # run on new version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install build backend
        run: python -m pip install --upgrade pip build

      - name: Build sdist and wheel
        run: python -m build

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

publish-testpypi:
  needs: build
  runs-on: ubuntu-latest
  environment:
    name: testpypi
    url: https://test.pypi.org/project/transformer-ranker/
  permissions:
    id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Upload to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/transformer-ranker/
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
