name: Publish transformer-ranker to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # run only on new version tags v0.1.3

jobs:
  build-distribution:
    name: Build sdist and wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: pip install --upgrade pip build

      - name: Build package
        run: python -m build

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-testpypi:
    name: Publish Python distribution to TestPyPI
    needs: build-distribution
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/transformer-ranker/
    permissions:
      id-token: write

    steps:
      - name: Download distribution artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Upload to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Verify installation from TestPyPI
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple transformer-ranker
          python -c "import transformer_ranker"

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    needs: publish-to-testpypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/transformer-ranker/
    permissions:
      id-token: write

    steps:
      - name: Download distribution artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
