name: Unit tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - "examples/**"
    - ".gitignore"
    - "README.md"
    - "LICENSE"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - "examples/**"
    - ".gitignore"
    - "README.md"
    - "LICENSE"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: pip install .[testing]

      - name: Run pytest
        run: pytest
